spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/kimoota?serverTimezone=UTC
    username: kimoota
    password: kimoota

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


  profiles:
    include: oauth
